# This is a basic workflow to help you get started with Actions

name: Build Page from source repo

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout homepage source code
      - uses: actions/checkout@main
        with:
          repository: Ghostling225/Homepage-Source
          path: source/

      # Install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 16.x
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: x64

      # Installs project dependencies and builds bundle with npm.
      - name: NPM build
        run: |
          cd $GITHUB_WORKSPACE/source
          npm install
          npm run build
          
      # Sets up an output git repo and commits the build.
      - name: Copy built page
        run: |
          cd $GITHUB_WORKSPACE
          mkdir out
          cd out
          
          git config --global init.defaultBranch main
          
          git init
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git remote add github git@github.com:Ghostling225/ghostling225.github.io.git
          
          cp -r ../source/build/* ./
          git add ./*
          git commit -m "Automatic Pages build update"
          git push github main
