# This is a basic workflow to help you get started with Actions

name: Build Page from source repo

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        with:
          repository: Ghostling225/Homepage-Source



      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 16.x
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: x64
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: $GITHUB_WORKSPACE/package-lock.json # optional


      
      # Runs a single command using the runners shell
      - name: NPM build
        run: |
          cd $GITHUB_WORKSPACE
          npm run build
